# Generated by Django 5.1.7 on 2025-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_files_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
