# Generated by Django 5.1.7 on 2025-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
