# Generated by Django 5.1.7 on 2025-04-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadfiles_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='text',
        ),
    ]
