# Generated by Django 5.1.7 on 2025-04-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadfiles_father_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='authorized_users',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
