# Generated by Django 5.1.7 on 2025-05-28 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_uploadfiles_authorized_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
