# Generated by Django 5.1.7 on 2025-05-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_files_uploadfiles_date_alter_uploadfiles_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='date',
        ),
    ]
