# Generated by Django 5.1.7 on 2025-05-28 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_uploadfiles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 0, 10, 21, 115732)),
            preserve_default=False,
        ),
    ]
