# Generated by Django 5.1.7 on 2025-05-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_uploadfiles_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='date',
            new_name='last_changes_date',
        ),
    ]
