# Generated by Django 5.1.7 on 2025-05-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='text',
        ),
    ]
