# Generated by Django 5.1.7 on 2025-05-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_notifications_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='recipient',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='text',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
