# Generated by Django 5.1.7 on 2025-05-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notifications_recipient_notifications_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='text',
        ),
    ]
