# Generated by Django 5.1.7 on 2025-05-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notifications_recipient_notifications_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='UpdateNotifications',
        ),
    ]
